version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Yolo.123
      MYSQL_DATABASE: huasoftware
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    restart: always
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://root:huasoftware_password@db/huasoftware
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
